### ISSUE TITLE
Large layouts lag

### ISSUE THREAD

**Issue by ZonKY0** [OndrejNepozitek/KitchenDesigner#13]
so I made a really large layout.
and the more objects I placed in said layout to less frames I have.
currently have a save running on only 5 fps.
while normally I run on 100
while playing the day the frames increase to like times 10 so its probably only an issue in the build phase.
my best guess would be that it has to do with the game going into a feed back loop checking for available tables.
and so if there was a way for the game to only check for available tables when your actually going to start the day it would help out a lot.
because atm you basically cant really rearrange your kitchen because of the lag.

It's probably more noticeable on large maps because it needs to check more tiles for tables
 
would appreciate it if this can be confirmed or if there's anything I should change to solve this issue.

**Comment by OndrejNepozitek** [comment]
Hey, thanks for the report but I'm afraid this is out of scope for the Kitchen Designer mod. I mostly don't change the vanilla behaviour of the game, just generate the layout. I think it should be possible to write a mod that would optimize the performance on large layouts because the vanilla layouts are quite small so it's not an issue in the game without mods. You might be able to find some help on the game discord in the modding section as there are often people willing to investigate mod ideas.

**Comment by ZonKY0** [comment]
I see, I assumed that since you have/had the large layout detect table fix in past versions of the mod that you could enable.
that you where altering that part of the vanilla game but I understand that if that's not something you doing its probably out of the scope of this mod

anyways thx for the reply I suppose these extreme size layouts might be to much for this game in the 1st place
